plugins {
      id 'java'
      id 'application'
      id 'jacoco'
}

dependencies {
	testImplementation 'org.assertj:assertj-core:3.27.7'
	testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

repositories {
	mavenCentral()
}

application {
	mainClass = 'ch.bbw.m450.tictactoe.TicTacToeMain'
}

test {
      useJUnitPlatform()
      finalizedBy jacocoTestReport
}

jacocoTestReport {
      dependsOn test
      reports {
              xml.required = true
              html.required = true
      }
}

run {
	standardInput = System.in
}
